name: phoenix_socket_example
description: A PhoenixSocket example
version: 0.0.2
homepage: https://www.github.com/matehat/phoenix-socket-dart
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  phoenix_socket:
    path: ../

  uuid: ^4.5.1

dev_dependencies: {}
